default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db

development:
  <<: *default
  database: hertz_development
  username: postgres
  password:

test:
  <<: *default
  database: hertz_test
  username: postgres
  password:
  host: db
  port: 5432

production:
  <<: *default
  database: hertz_production
  username: hertz
  password: <%= ENV['OCTANE-BACKEND_DATABASE_PASSWORD'] %>
